webtalk_init -webtalk_dir D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 13 00:44:07 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "938903dc-bac8-4fc9-8b52-910814c716eb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a1348adfdc9e46d19e8927fc14250b7f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "124" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2296 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "41 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "8" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.69_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 501442232 -regid "" -xml D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
