# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.cache/wt [current_project]
set_property parent.project_path D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Konwersja_RGB_YCbCr/ip_repo_delayed
  d:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Wyznaczanie_srodka_ciezkosci/divider_32_20_0
} [current_project]
set_property ip_output_repo d:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/imports/new/centroid.v
  D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/imports/sources/delayLinieBRAM_WP.v
  D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/imports/new/delay_block.v
  D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/imports/new/delay_line.v
  D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/new/median5x5.v
  D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/new/vis_centroid.v
  D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/new/vp.v
}
read_ip -quiet D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_v2_0/rgb2ycbcr_v2_0.xci

read_ip -quiet D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.xci

read_ip -quiet D:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
set_property used_in_implementation false [get_files -all d:/Dokumenty/AiR_rok_3/S6/Systemy_rekonfigurowalne/Operacje_kontekstowe/project/hdmi_vga_zybo.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top vp -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vp.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vp_utilization_synth.rpt -pb vp_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
